### ISSUE TITLE
Bug: Aria-live content is not acting as "assertive”

### ISSUE THREAD

**Issue by DiogoRDuarte** [feedzai/AutoVizuA11y#17]
**Describe the bug**
All the aria-live content is no longer acting as "assertive”.

**To Reproduce**
1. Set you keyboard focus to either a chart or data element;
2. As the screen reader is reading either the description or label, press a shortcut from “Statistical insights”.
3. Verify that the screen reader **does not** immediately reads the requested information, only after finishing what it was reading before.

**Expected behavior**
 If a shortcut is pressed (e.g. asking for the max, changing description type) the screen reader should stop mid sentence and read the requested content.

**Evidence**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox, Chrome, Safari
 - Screen Reader: VoiceOver
 - AutoVizuA11y Version: 1.0.3

**Comment by JoaoTMDias** [comment]
Hi Diogo, can you check if you still need this opened issue? If note, please close it! Thanks!

**Comment by DiogoRDuarte** [comment]
Aria-live content has been broken on VoiceOver for some months now, without a concrete solution on the developer side.
https://www.applevis.com/comment/168342#comment-168342
