### ISSUE TITLE
Feature: Enable visual customization of Shortcut Guide

### ISSUE THREAD

**Issue by DiogoRDuarte** [feedzai/AutoVizuA11y#21]
**Is your feature request related to a problem? Please describe.**
The Shortcut Guide provided by the tool is not customizable. This might be a block for some developers whose interfaces need to follow a specific visual style

**Describe your proposed solution**
For the Shortcut Guide to accept custom CSS styles through its React properties.

**Describe alternatives you've considered**
Only this solution was considered.

**Additional context**
![image 1](https://github.com/feedzai/AutoVizuA11y/assets/70715371/84e7d4bb-62a8-45f7-82f6-718ede24171d)

**Comment by JoaoTMDias** [comment]
Hi Diogo, can you check if you still need this opened issue? If note, please close it! Thanks!
